# Generated by Django 6.0.5 on 2026-06-24 09:33

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shorten', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='long_urls',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='long_urls',
            name='clicks',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='long_urls',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='long_urls',
            name='short_code',
            field=models.CharField(default='temp', max_length=20, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='long_urls',
            name='long_url',
            field=models.URLField(max_length=2048),
        ),
    ]
